### ISSUE TITLE
Multilang support

### ISSUE THREAD

**Issue by TheDoctor0** [TheDoctor0/CSGOMod#1]
Similarly to CoDMod it would be great to add multilang support.

- [x]  Core
- [x]  Clans
- [x]  Ranks
- [x]  Accounts
- [x]  Assist and revenge
- [x]  Operations
- [x]  Server menu
- [x]  Transfer
- [x]  VIP and SVIP

**Comment by Damigeana** [comment]
I can help you with the translation.

**Comment by TheDoctor0** [comment]
Hello @Damigeana, do you want to help with multilang support or just the translations?

If you want to help with multilang support you can fork this repository and start making changes similar to those:
https://github.com/TheDoctor0/CoDMod/compare/feature-multilang

If not you'll need to wait for me to do it, so single lang file for whole mod will be available.
Then translations to any language beside polish and english will be appreciated.

**Comment by Damigeana** [comment]
I was started to do it on on sma code.

În vin., 3 iul. 2020 la 08:39, Dawid Janik <notifications@github.com> a
scris:

**Comment by ksm200** [comment]
I can translate to Brazilian Portuguese

**Comment by TheDoctor0** [comment]
Four more plugin to go.
If you want you can start to translate [csgomod.txt](https://github.com/TheDoctor0/CSGOMod/blob/master/cstrike/addons/amxmodx/data/lang/csgomod.txt).

**Comment by Damigeana** [comment]
I’m gona do that sunday or next week since i’m working long shift :(

**Comment by TheDoctor0** [comment]
It will take some time to finish the rest, you you'll have plenty of time.

**Comment by regener** [comment]
Hi!
I have already started to translate your mod, but I don't have the time to finish it.
I didn't inclue the menu buttons (just the Exit), but you can use the default common.txt without replicating the translations to your mod. Also I don't speak polish, so I just coped the texts from the sma to the lang file.
Mistakes in coding are guaranteed, feel free to modify, since this is your mod. :)

csgo_accounts.sma:
https://pastebin.com/Hd3Yg8pK
The lang file for it:
https://pastebin.com/fmRy4KwU

The other SMA-s are already included in your last updates, so there is no point to post them.
I will translate to Hungarian if I will have some free time away from work (no ETA).

On the other side I think it would be good to separate the Clan plugin from the others, since if someone doesn't run that then there is no need for the translation to be loaded (I know it is just some bytes of memory, but anyway).

I don't know if any of that helps, but I hope so :D

**Comment by TheDoctor0** [comment]
@regener, thanks for help. I made only some minor adjustments.

> On the other side I think it would be good to separate the Clan plugin from the others
Native for getting clan name is used by other plugins, so disabling clans is not really possible without making modification.

**Comment by TheDoctor0** [comment]
All that's left is the core plugin 😄

**Comment by TheDoctor0** [comment]
Multilang support has been finally finished.

@ksm200 @Damigeana @regener 
I'll release the final 2.0.0 version in saturday, so if you want me to include some translations (beside english and polish)
you can send me them or create a [pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request). Of course I'll also accept them later and release in a next version.
