### ISSUE TITLE
Molotov model bug after issue #137

### ISSUE THREAD

**Issue by NiceFeatures** [TheDoctor0/CSGOMod#139]
After patch #137, molotov cannot assume the correct model, randomly assuming the model of the previous weapon, when pausing the core plugin the model is correct in molotov.

**Comment by TheDoctor0** [comment]
I just checked it on my test server with both submodels enabled and disabled.
This does not seem to be the case, because Molotov works fine.

Can you record a video of it happening?
Also, do you have any plugins installed on the server beside CS:GO mod?

**Comment by NiceFeatures** [comment]
I'm using this molotov plugin, and the problem is only if I don't pause the core, if I pause it, the model is normal.

`https://pastebin.com/raw/Xe1UUWvg`

**Comment by TheDoctor0** [comment]
Well, the problem is that you use a custom plugin for Molotov.
If want it to work properly you would need to make changes like [here](https://github.com/TheDoctor0/CSGOMod/blob/master/cstrike/addons/amxmodx/scripting/csgo_core.sma#L2626), to ignore the Molotov when the weapon model is set.
Unfortunately, I do not provide support for anything that is not included in this mod, so if you want to use this plugin, you will have to figure it out by yourself.

I assume that you want to have the Molotov as a new selectable weapon in HUD. I had plans to do it, but I know that I won't have time in the near future. If you have the skills to pull this of and want to share it later, I'll gladly accept the improved version of the Molotov plugin in form of [pull-request](https://github.com/TheDoctor0/CSGOMod/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc).

**Comment by NiceFeatures** [comment]
Done.
