### ISSUE TITLE
new error critical

### ISSUE THREAD

**Issue by ksm200** [TheDoctor0/CSGOMod#32]
server shotdown on player dead

http://www.mediafire.com/file/7g7x82szm5rczj7/csgomod.dem/file

archive .dem

and logs
```
L 08/24/2020 - 17:12:38: [FAKEMETA] Invalid entity
L 08/24/2020 - 17:12:38: [AMXX] Run time error 10 (plugin "csgo_ranks.amxx") (native "pev") - debug not enabled!
L 08/24/2020 - 17:12:38: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
```

**Comment by TheDoctor0** [comment]
This is the latest version of ranks plugin?

Please add `debug` to `csgo_ranks.amxx` so error stack will be shown in logs.

**Comment by ksm200** [comment]
L 08/24/2020 - 17:25:43: [FAKEMETA] Invalid entity
L 08/24/2020 - 17:25:43: [AMXX] Displaying debug trace (plugin "csgo_ranks.amxx", version "2.0.0")
L 08/24/2020 - 17:25:43: [AMXX] Run time error 10: native error (native "pev")
L 08/24/2020 - 17:25:43: [AMXX]    [0] csgo_ranks.sma::display_hud (line 444)

**Comment by TheDoctor0** [comment]
It was a surprise for me that suicide by dropping from height crashed server, but not by using `kill` command.
I was even more surprised when the problem occurred after disabling all mod plugins.

After some in-depth debugging I discovered that this crash was caused by a missing sound `common/bodysplat.wav` (removed with unprecacher module). To be honest I really wasn't expecting this as sounds like that are client-side not server-side.
Really nice find 👍
