### ISSUE TITLE
Skins problem

### ISSUE THREAD

**Issue by LycaNiaNN** [TheDoctor0/CSGOMod#65]
Hey man, every time when i try to change the skins (remove or something else) i recive some bugs like:  lang on the server disappears:
Pics:
https://steamuserimages-a.akamaihd.net/ugc/1625193014913859847/A8D419396A0126BB406987A6958164B272215C82/
https://steamuserimages-a.akamaihd.net/ugc/1625193014913859625/691E4463285342EFE267AF39575B994CBEE97FFC/

After that, i recive to many errors in server console like:
L 09/13/2020 - 22:33:46: [CS:GO Clans] Init SQL Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) (2002)
L 09/13/2020 - 22:33:46: [CS:GO Accounts] Init SQL Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) (2002)

All I want is to wipe some skins because there are too many and leave some after that replace them. But when i make some change i recive that...you can see UP.

**Comment by TheDoctor0** [comment]
> Hey man, every time when i try to change the skins (remove or something else) i recive some bugs like: lang on the server disappears

What language are you using? It probably means that some translation strings are missing. I only made english and polish translations and only those were tested by me.

> L 09/13/2020 - 22:33:46: [CS:GO Clans] Init SQL Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) (2002)
L 09/13/2020 - 22:33:46: [CS:GO Accounts] Init SQL Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) (2002)

That suggests that probably core plugin is shutting down so database cvars are not being registered.
If you want to remove some skins just remove them from `csgo_skins.ini`. 
Do not remove any files because submodels are used and one model can contain up to 40 skins.

**Comment by LycaNiaNN** [comment]
What language are you using? It probably means that some translation strings are missing. I only made english and polish translations and only those were tested by me.
> ENG
That suggests that probably core plugin is shutting down so database cvars are not being registered.
> Yes, i know, but that error appers to me when i made skin modification.
If you want to remove some skins just remove them from csgo_skins.ini.
Do not remove any files because submodels are used and one model can contain up to 40 skins.
> I know how to make, but i want to put another models, after i make 2-3-4 models, i recive errors.
I want to put 1 skin for 1 knife...

**Comment by TheDoctor0** [comment]
Check logs in `csgo-error.log`, because clearly there is some problem model changes that you made.

**Comment by LycaNiaNN** [comment]
It was a problem from me.
Thx for help.
