### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by LucijasO** [TheDoctor0/CSGOMod#67]
Hey, when im buying the XM1014 shotgun and im trying to reload my server just crashes and it gives no logs in logs.txt. and also the skin market bugs out when im trying to withdraw my skin.

**Comment by TheDoctor0** [comment]
I'm 95% sure that it's yet again caused by a missing sound removed by unprecacher.
It's sometimes really weird how this module works.
Nevertheless, I'll try to investigate and fix it today.

About market confirmation, it's [fixed](https://github.com/TheDoctor0/CSGOMod/commit/5a64f7dfd17752e031754452734fb5fb3e3911ce).

**Comment by LucijasO** [comment]
Okay, thanks!
